name: Build

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        # Use blst tag to allow go and bazel builds for blst.
        run: go build -v ./...
        env:
           CGO_CFLAGS: "-O2 -D__BLST_PORTABLE__"
        # fuzz leverage go tag based stubs at compile time.
        # Building and testing with these tags should be checked and enforced at pre-submit.
      - name: Get dependencies
        run: |
          bazel build //cmd/validator:image_bundle --config=release 

# Tests run via Bazel for now...
#      - name: Test
#        run: go test -v ./...
