name: Build

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Bazel build
        run: |
          bazel build //cmd/validator:image_bundle --config=release 
